ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/upstream-hash-by: "$remote_addr"
  hosts:
    - host: gsbcsmconsole.dpdpa.osd.co.th
      paths:
        - /
  tls:
    - secretName: ingress-nginx-prod-tls

replicaCount: 2
autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

resources:
  requests:
    cpu: 50m
  limits:
    cpu: 150m

